import React, { useState, useEffect, useCallback } from 'react';
import StaffLayout from '@/components/layout/StaffLayout';
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardFooter, 
  CardHeader, 
  CardTitle 
} from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { 
  Dialog, 
  DialogContent, 
  DialogDescription, 
  DialogFooter, 
  DialogHeader, 
  DialogTitle, 
  DialogTrigger 
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import { ScrollArea } from "@/components/ui/scroll-area"
import { toast } from 'sonner';
import { useForm } from 'react-hook-form';
import { zodResolver } from "@hookform/resolvers/zod"
import * as z from "zod";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { 
  PrinterIcon, 
  ImagePlus, 
  Edit, 
  Trash2, 
  Search, 
  Plus, 
  Wand2, 
  Loader2,
  Eye,
  EyeOff,
  Copy,
  Download,
  Upload,
  AlertCircle,
  CheckCircle,
  XCircle,
  ArrowDown,
  ArrowUp,
  FileImage,
  Text,
  Tag,
  ShoppingCart,
  Percent,
  Ruler,
  Layers,
  Settings,
  Share2,
  HelpCircle,
  LayoutDashboard,
  Megaphone,
  Store,
  Boxes,
  Barcode,
} from 'lucide-react';
import { Product, ProductImage, ProductWithImages } from '@/types';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { mapDbProductToProduct, mapDbProductImageToProductImage } from '@/utils/typeMappers';
import ProductLabelPrint from '@/components/admin/printing/ProductLabelPrint';
import AIDescriptionGenerator from '@/components/ai/AIDescriptionGenerator';
import ProductPhotoUpload from '@/components/admin/products/ProductPhotoUpload';

// Define a schema for the product form
const productFormSchema = z.object({
  name: z.string().min(2, { message: "Name must be at least 2 characters." }),
  title: z.string().optional(),
  description: z.string().optional(),
  price: z.number({ invalid_type_error: "Price must be a number." }).min(0, { message: "Price must be greater than 0." }),
  originalPrice: z.number({ invalid_type_error: "Original price must be a number." }).optional(),
  category: z.string().min(2, { message: "Category must be at least 2 characters." }),
  subCategory: z.string().optional(),
  condition: z.enum(['new', 'likeNew', 'good', 'fair'], {
    required_error: "Please select a condition.",
  }),
  size: z.string().optional(),
  color: z.string().optional(),
  brand: z.string().optional(),
  barcode: z.string().optional(),
  status: z.enum(['available', 'reserved', 'sold'], {
    required_error: "Please select a status.",
  }),
  imageUrl: z.string().optional(),
  featured: z.boolean().default(false),
});

// Define the Product interface
interface ProductType {
  id: string;
  name: string;
  title?: string;
  description?: string;
  price: number;
  originalPrice?: number;
  category: string;
  subCategory?: string;
  condition: string;
  size?: string;
  color?: string;
  brand?: string;
  barcode: string;
  status: string;
  imageUrl?: string;
  featured?: boolean;
}

const ProductManager = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [images, setImages] = useState<ProductImage[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [isAddingProduct, setIsAddingProduct] = useState(false);
  const [isEditingProduct, setIsEditingProduct] = useState(false);
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isAIModalOpen, setIsAIModalOpen] = useState(false);
  const [isPrinting, setIsPrinting] = useState(false);
  const [isDescriptionLoading, setIsDescriptionLoading] = useState(false);
  const [isImageUploading, setIsImageUploading] = useState(false);
  const [aiGeneratedDescription, setAiGeneratedDescription] = useState<string | null>(null);
  const [aiGeneratedImages, setAiGeneratedImages] = useState<string[]>([]);
  const [sortColumn, setSortColumn] = useState<keyof ProductType | null>('name');
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('asc');
  const [showHidden, setShowHidden] = useState(false);
  const [selectedImages, setSelectedImages] = useState<string[]>([]);
  const [isImagePreviewOpen, setIsImagePreviewOpen] = useState(false);
  const [selectedImageUrl, setSelectedImageUrl] = useState<string | null>(null);
  const [isImageActionsOpen, setIsImageActionsOpen] = useState(false);
  const [isImageBulkActionsOpen, setIsImageBulkActionsOpen] = useState(false);
  const [isImageBulkDeleteConfirmOpen, setIsImageBulkDeleteConfirmOpen] = useState(false);
  const [isProductDeleteConfirmOpen, setIsProductDeleteConfirmOpen] = useState(false);
  const [isProductBulkActionsOpen, setIsProductBulkActionsOpen] = useState(false);
  const [isProductBulkDeleteConfirmOpen, setIsProductBulkDeleteConfirmOpen] = useState(false);
  const [selectedProducts, setSelectedProducts] = useState<string[]>([]);
  const [isProductActionsOpen, setIsProductActionsOpen] = useState(false);
  const [isProductVisibilityActionsOpen, setIsProductVisibilityActionsOpen] = useState(false);
  const [isProductBulkVisibilityActionsOpen, setIsProductBulkVisibilityActionsOpen] = useState(false);
  const [isProductBulkVisibilityConfirmOpen, setIsProductBulkVisibilityConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmOpen, setIsProductBulkVisibilityHiddenConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmOpen, setIsProductBulkVisibilityVisibleConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsOpen, setIsProductBulkVisibilityHiddenActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsOpen, setIsProductBulkVisibilityVisibleActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenOpen, setIsProductBulkVisibilityVisibleConfirmHiddenOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleOpen, setIsProductBulkVisibilityHiddenConfirmVisibleOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleOpen, setIsProductBulkVisibilityVisibleConfirmVisibleOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenOpen, setIsProductBulkVisibilityHiddenConfirmHiddenOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsHiddenOpen, setIsProductBulkVisibilityVisibleActionsHiddenOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsVisibleOpen, setIsProductBulkVisibilityHiddenActionsVisibleOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleOpen, setIsProductBulkVisibilityVisibleConfirmVisibleOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenOpen, setIsProductBulkVisibilityHiddenConfirmHiddenOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleOpen, setIsProductBulkVisibilityVisibleActionsVisibleOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenOpen, setIsProductBulkVisibilityHiddenActionsHiddenOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsHiddenActionsOpen, setIsProductBulkVisibilityVisibleActionsHiddenActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsVisibleActionsOpen, setIsProductBulkVisibilityHiddenActionsVisibleActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen, setIsProductBulkVisibilityHiddenActionsHiddenActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsActionsOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityVisibleConfirmVisibleConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen, setIsProductBulkVisibilityHiddenConfirmHiddenConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmConfirmOpen] = useState(false);
  const [isProductBulkVisibilityVisibleActionsVisibleActionsActionsActionsActions
